# Generated by Django 4.2.7 on 2024-04-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pen', 'Pendiente'), ('abi', 'Abierta'), ('cer', 'Cerrada')], default='pen', max_length=3)),
            ],
            options={
                'verbose_name': 'Election Handler',
                'verbose_name_plural': 'Election Handlers',
            },
        ),
    ]
