# Generated by Django 4.2.7 on 2024-04-19 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0001_initial'),
        ('voting', '0002_electionhandler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='districts.district')),
                ('political_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='voting.politicalparty')),
            ],
            options={
                'verbose_name': 'Vote',
                'verbose_name_plural': 'Votes',
            },
        ),
    ]
