# Generated by Django 4.2.7 on 2024-04-19 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='political_party',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='voting.politicalparty'),
        ),
    ]
